### ISSUE TITLE
导出的配置如果能保留会更舒服

### ISSUE THREAD

**Issue by Wetoria** [frostime/sy-bind-mdfile#1]
目前每一篇文档都需要重新选择导出的配置，文档的目录、修改assets目录，以及修改asset前缀，如果能记住会更舒服一点。

更进一步的情况，也许能选择历史记录可能会更好。

比如我手里现在有CE的文档仓库和我自己的站点，一共两个目录。

除了每次导出前需要选择文件夹以外，切换站点还需要重新选择不同的目录

**Comment by frostime** [comment]
可以考虑讲一些配置缓存起来，然后在配置某个文档的时候直接使用吧。

**Comment by Wetoria** [comment]
这个配置应该是“全局”的说，并且每篇文档能记住上一次的设置。我是会这样设计，不过我知道f佬你应该没空处理这些细节←_←

**Comment by Wetoria** [comment]
这个配置应该是“全局”的说，并且每篇文档能记住上一次的设置。我是会这样设计，不过我知道f佬你应该没空处理这些细节←_←
