### ISSUE TITLE
导出的是kramdown吗

### ISSUE THREAD

**Issue by HibernalGlow** [frostime/sy-bind-mdfile#3]
我看表格是思源语法的表格https://github.com/siyuan-note/siyuan/issues/12223#issue-2458883211
但思源本身导入md好像不支持自身的表格合并单元格，如果能做适配就好了

**Comment by HibernalGlow** [comment]
![image](https://github.com/user-attachments/assets/b0988086-509c-429f-b27b-135bfcc9c862)
我测试了，有的表格支持，有的表格不支持，好像

**Comment by frostime** [comment]
目前走的是后端的 kernal api，导出的应该是标准 md 格式

**Comment by HibernalGlow** [comment]
有些文档我导出来确实是有合并单元格

**Comment by AvoidantPerDis** [comment]
而且神奇的是，第一遍打开是没有的，第二遍打开就有了

**Comment by HibernalGlow** [comment]
可能跟我原本文档是通过粘贴导入的html表格有关

**Comment by frostime** [comment]
> 目前走的是后端的 kernal api，导出的应该是标准 md 格式

这个我就不太清楚了，导出的 md 我基本上没做处理，可能是思源内部的奇妙操作了。🤨
